name: Deploy Backend - AWS Lambda

on:
    push:
        branches:
            - main
        paths:
            - 'backend/*'
            - 'backend/**'
            - '.github/workflows/backend-deploy.yml'
            - 'cdk/*'
            - 'cdk/**'

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}  
  AWS_DEFAULT_OUTPUT: json
  API_GATEWAY_URL: ${{ vars.API_GATEWAY_URL }}
  API_GATEWAY_ORIGIN_PATH: ${{ vars.API_GATEWAY_ORIGIN_PATH }}

permissions:
  id-token: write
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with: 
                node-version: 20.x

            - name: Setup python 3.11
              uses: actions/setup-python@v4
              with:
                    python-version: 3.11
            
            - name: Setup Docker
              uses: docker/setup-buildx-action@v3

            - name: Instal cdk and Python dependencies
              run: |
                cd cdk
                npm install -g aws-cdk                
                pip install -r requirements.txt

            - name: Setup AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ vars.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                role-duration-seconds: 1200
                role-session-name: github-actions

            - name: CDK Deploy
              run: |
                cd cdk
                cdk deploy --require-approval never
              env:
                CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
                CDK_DEFAULT_REGION: ${{ vars.AWS_REGION }}
                FE_BUCKET_NAME: ${{ vars.FE_BUCKET_NAME }}

